### ISSUE TITLE
can not figure out why dom-pool is faster than document.createElement

### ISSUE THREAD

**Issue by jabez128** [ChrisAntaki/dom-pool#3]
I saw the jsperf result and just can not figure out why dom-pool is faster than document.createElement. Maybe I missed some important point.  Is there anyone can give me some hint? :)

**Comment by navaru** [comment]
Let's assume you have a infinite scroll UI and display 10 items at a time, with `document.createElement` you create new elements on every refresh, while with `dom-pool` you create 10 elements and reuse them. Basically you avoid creating new elements and garbage collect the old ones, which is more expensive then reusing unused elements.

Makes sense?

**Comment by jabez128** [comment]
@TEugen nice explanation, thx
