### ISSUE TITLE
Integrate with d3

### ISSUE THREAD

**Issue by hy9be** [ChrisAntaki/dom-pool#6]
Hi, I am trying to reduce the overhead of creating and removing SVG elements in one of my project.  Your lib looks quite promising. But I am not sure if there is a good way to make it work with d3's ``append`` paradiam, in which I do not have control on the direct DOM creation:

```
projectpaths.enter().append('path')
  .attr("transform", "translate(0," + height + ")")
  .attr('class','projects')
  .attr('d', function(datum) {
    var date = parseDate(datum.month);
    var capacity = +datum.capacity;
    return drawturbine(x(date), y_invert(capacity));
  })
```

**Comment by ChrisAntaki** [comment]
It looks like you might be able to pass "append()" a Function instead of a string. That function just needs to return a DOM element, and could probably interact with a pool of DOM elements.
https://github.com/d3/d3-selection/blob/master/README.md#selection_append

**Comment by hy9be** [comment]
Got it. I will give it a try. Thanks!
